HW27-1
skayKatya/PlaywrightKate pull request #7
Opened 2024-08-14 18:51 UTC by skayKatya

2024-08-15 18:42 UTC, sttaran requested changes

2024-08-15 18:42 UTC, sttaran commented on state/user1.json
add it to gitignore

2024-08-15 18:42 UTC, sttaran commented on state/user1.json
and remove it

2024-08-15 18:42 UTC, sttaran commented on tests/HW27-1/HW27-1-profileInfo.spec.js
> +            await page.pause()
check if value was mocked on UI

2024-08-16 09:27 UTC, skayKatya commented on tests/HW27-1/HW27-1-profileInfo.spec.js
> +            await page.pause()
after adding
 await page.reload()
 await page.pause() -> I saw new values 
 "name": "test",
  "lastName": "Nework"

2024-08-16 09:29 UTC, skayKatya commented on tests/HW27-1/HW27-1-profileInfo.spec.js
> +            await page.pause()
![2024-08-16_12h29_14](https://github.com/user-attachments/assets/5e7c7650-11c0-4049-9524-b75f18a1edb7)

2024-08-16 09:31 UTC, skayKatya commented on state/user1.json
done

2024-08-16 12:41 UTC, merged